name: pipeline_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=38.0.3
  - cuda-cccl=12.6.37
  - cuda-cccl_win-64=12.6.37
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.68
  - cuda-opencl-dev=12.6.68
  - cuda-profiler-api=12.6.68
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - filelock=3.8.0
  - freetype=2.12.1
  - glfw
  - gmpy2=2.1.2
  - idna=3.4
  - imageio
  - imgui
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lcms2=2.14
  - lerc=4.0.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.7.68
  - libcurand-dev=10.3.7.68
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.14
  - libffi=3.4.2
  - libjpeg-turbo=2.1.4
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.68
  - libnvfatbin-dev=12.6.68
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.38
  - libsqlite=3.40.0
  - libtiff=4.4.0
  - libuv=1.48.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpir=3.0.0
  - mpmath=1.2.1
  - msys2-conda-epoch=20160418
  - networkx=2.8.8
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openjpeg=2.5.0
  - openssl=3.0.7
  - pillow=9.2.0
  - pip=22.3.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - PyGLM
  - PyOpenGL
  - pyopenssl=22.1.0
  - pysocks=1.7.1
  - python=3.11.0
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - plyfile
  - requests=2.28.1
  - setuptools=65.5.1
  - tbb=2021.7.0
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022f
  - ucrt=10.0.22621.0
  - urllib3=1.26.11
  - vc=14.3
  - vs2015_runtime=14.32.31332
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zstd=1.5.2
  - pip:
    - click==8.1.7
    - contourpy==1.3.1
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - fonttools==4.55.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - kiwisolver==1.4.7
    - matplotlib==3.9.2
    - protobuf==5.28.3
    - pyparsing==3.2.0
    - sentry-sdk==2.18.0
    - setproctitle==1.3.4
    - smmap==5.0.1
    - sympy==1.13.3
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - wandb==0.17.2
